name: DemocracyPost
version: '${version}'
main: io.github.md5sha256.democracypost.DemocracyPost
api-version: '1.20'
authors: [andrewandy]
depend: ['Vault', 'Essentials']
softdepend: ['HeadDatabase']

commands:
  post open:
    description: "Display a user's post box for them"
    permission: "democracypost.open"
  post view:
    description: "View a user's post box"
    permission: "democracypost.view"

libraries:
  - 'org.mariadb.jdbc:mariadb-java-client:3.4.0'
  - 'com.zaxxer:HikariCP:5.1.0'